<a href="https://colab.research.google.com/github/databyhuseyn/MachineLearning/blob/main/scikit_learn_107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
!wget https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/main/heart-disease.csv

--2024-06-07 17:13:15--  https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/main/heart-disease.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11328 (11K) [text/plain]
Saving to: ‘heart-disease.csv’

heart-disease.csv   100%[===================>]  11.06K  --.-KB/s    in 0s      

2024-06-07 17:13:15 (33.0 MB/s) - ‘heart-disease.csv’ saved [11328/11328]



In [ ]:
df = pd.read_csv('/content/heart-disease.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [ ]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
X = df.drop('target', axis=1)
y = df['target'].copy()
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier


rnd_forest = RandomForestClassifier()
rnd_forest.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
rnd_forest.score(X_train, y_train) * 100

100.0

In [ ]:
rnd_forest.score(X_test, y_test) * 100

85.24590163934425

In [ ]:
X_test.iloc[0]

age          57.0
sex           1.0
cp            0.0
trestbps    150.0
chol        276.0
fbs           0.0
restecg       0.0
thalach     112.0
exang         1.0
oldpeak       0.6
slope         1.0
ca            1.0
thal          1.0
Name: 179, dtype: float64

In [ ]:
X_test.iloc[0].values.reshape(1, -1)

array([[ 57. ,   1. ,   0. , 150. , 276. ,   0. ,   0. , 112. ,   1. ,
          0.6,   1. ,   1. ,   1. ]])

In [ ]:
y_test.iloc[0]

0

In [ ]:
rnd_forest.predict(X_test.iloc[0].values.reshape(1, -1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
rnd_forest.predict([X_test.iloc[0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
!wget https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/main/car-sales-extended.csv


--2024-06-07 17:13:19--  https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/main/car-sales-extended.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26277 (26K) [text/plain]
Saving to: ‘car-sales-extended.csv’

car-sales-extended. 100%[===================>]  25.66K  --.-KB/s    in 0.002s  

2024-06-07 17:13:20 (13.0 MB/s) - ‘car-sales-extended.csv’ saved [26277/26277]



In [ ]:
car_sales = pd.read_csv("/content/car-sales-extended.csv")
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X = car_sales.drop("Price", axis = 1)
y = car_sales['Price'].copy()
X

Make Colour  Odometer (KM)  Doors
0     Honda  White          35431      4
1       BMW   Blue         192714      5
2     Honda  White          84714      4
3    Toyota  White         154365      4
4    Nissan   Blue         181577      3
..      ...    ...            ...    ...
995  Toyota  Black          35820      4
996  Nissan  White         155144      3
997  Nissan   Blue          66604      4
998   Honda  White         215883      4
999  Toyota   Blue         248360      4

[1000 rows x 4 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train

Make Colour  Odometer (KM)  Doors
98   Toyota    Red         147455      4
326  Toyota   Blue         232912      4
534   Honda   Blue          35292      4
891  Nissan  Black          10148      4
434  Toyota  White          36463      4
..      ...    ...            ...    ...
611  Toyota  Black         136271      4
832  Toyota  White         100107      4
303  Toyota  White         134862      4
597  Nissan  White          20315      4
131  Toyota    Red          29689      4

[800 rows x 4 columns]

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [ ]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [ ]:
car_sales[['Make', 'Colour']]

Make Colour
0     Honda  White
1       BMW   Blue
2     Honda  White
3    Toyota  White
4    Nissan   Blue
..      ...    ...
995  Toyota  Black
996  Nissan  White
997  Nissan   Blue
998   Honda  White
999  Toyota   Blue

[1000 rows x 2 columns]

In [ ]:
cat_features = X_train.select_dtypes(include = ['object']).columns
cat_features

Index(['Make', 'Colour'], dtype='object')

In [ ]:
onehot_encoder = OneHotEncoder()
one_hot_data = onehot_encoder.fit_transform([cat_features])
one_hot_data

<1x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [ ]:
one_hot_data.toarray()

array([[1., 1.]])

In [ ]:
OrdinalEncoder().fit_transform(cat_features)

ValueError: Expected 2D array, got 1D array instead:
array=['Make' 'Colour'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer([
    ('one_hot',  OneHotEncoder(), cat_features)
], remainder = 'passthrough')

transformed_X_train = transformer.fit_transform(X_train)
feature_names = transformer.get_feature_names_out()

transformed_X_train_df = pd.DataFrame(transformed_X_train, columns = feature_names)
transformed_X_train_df

In [ ]:
transformed_X_test = transformer.transform(X_test)

transformed_X_test_df = pd.DataFrame(transformed_X_test, columns = feature_names)
transformed_X_test_df

In [ ]:
rnd_reg.fit(transformed_X_train_df, y_train)

In [ ]:
rnd_reg.score(transformed_X_train_df, y_train)

In [ ]:
rnd_reg.score(transformed_X_test_df, y_test)

# OrdinalEncoder

In [ ]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer([
    ('one_hot',  OrdinalEncoder(), cat_features)
], remainder = 'passthrough')


transformed_X_train = transformer.fit_transform(X_train)
feature_names = transformer.get_feature_names_out()

transformed_X_train_df = pd.DataFrame(transformed_X_train, columns = feature_names)
transformed_X_train_df

In [ ]:
transformed_X_test = transformer.transform(X_test)
feature_names = transformer.get_feature_names_out()

transformed_X_test_df = pd.DataFrame(transformed_X_test, columns = feature_names)
transformed_X_test_df

# Pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [ ]:
num_features = X_train.select_dtypes(include=[np.number]).columns
cat_features = X_train.select_dtypes(exclude=[np.number]).columns

In [ ]:
cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='constant', fill_value='Missing')),
    ('onehot', OneHotEncoder(handle_unknown = 'error'))
])

num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

transform = ColumnTransformer([
    ('num', num_pipeline, num_features),
    ('cat', cat_pipeline, cat_features)
], remainder = 'passthrough')